apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitflow-analyzer-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/panethjonathan8-ctrl/gitflow-gitops
    targetRevision: main
    path: k8s/helm/gitflow-analyzer
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitflow-analyzer-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
