apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitflow-analyzer-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    # Deleting this Application also deletes everything it manages in the
    # gitflow-analyzer-dev namespace. Prevents orphaned resources.
spec:
  project: default

  source:
    repoURL: https://github.com/panethjonathan8-ctrl/gitflow-gitops
    targetRevision: main
    path: k8s/helm/gitflow-analyzer
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitflow-analyzer-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
